/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-unnecessary-condition */
/* eslint-disable prettier/prettier */
/* eslint-disable security/detect-object-injection */
/* eslint-disable max-lines */
/* eslint-disable complexity */
"use server";

import { chartsData as dummyChartsData, metricCardsData as dummyMetricCardsData } from "@/lib/analytics-data";
import {
  SUPPORTED_CURRENCIES,
  USD_EXCHANGE_RATES,
  CURRENCY_INFO,
  type AnalyticsData,
  type MetricCardData,
  type ChartData,
  type ProfitAnalyticsApiResponse,
  type CurrencyPairAnalyticsApiResponse,
  type WalletAnalyticsApiResponse,
  type CustomerAnalyticsApiResponse,
  type MonthlyProfitAnalyticsApiResponse,
  type CountryAnalyticsApiResponse,
  type DemoDataReason,
  type SupportedCurrency,
  ChartDataItem,
  type ProductAnalyticsResponse,
  type TransactionAnalyticsResponse,
  type RevenueAnalyticsResponse,
} from "@/lib/analytics-types";
import type { ApiError } from "@/lib/types";
import { getValueFromCookie } from "@/server/server-actions";

const API_BASE_URL = process.env.NEXT_PUBLIC_ENDPOINT;

// ============================================================================
// General Metrics Whitelist - Metrics to show on main /dashboard/metrics page
// ============================================================================

/**
 * Whitelist of metric IDs that should appear on the main metrics page.
 * User-specific metrics should only appear on individual user detail pages.
 *
 * Note: These are base IDs without currency suffixes. The filtering logic
 * will match cards like "gross-revenue-all", "gross-revenue-ngn", etc.
 */
const GENERAL_METRIC_IDS = [
  // New Analytics Metrics
  "active-users-daily",
  "active-users-weekly",
  "active-users-monthly",
  "total-volume-gtv",
  "total-transaction-count-real",
  "avg-transaction-value",
  "avg-transactions-per-customer",

  "gross-revenue",
  "transaction-fees",
  "fx-sales",

  "total-transaction-count",
  "total-amount",
  "transaction-count",
  "amount",

  "total-wallets",
  "most-active-wallets",
  "regional-wallet-leader",
  "active-wallets",

  "top-pair-profit",
  "top-currency-pair-profit",
  "highest-conversion-rate",
  "highest-failure-rate",
  "best-success-rate",
  "worst-failure-rate",
  "outbound-amount",
  "outbound-volume",

  "top-sending-country",
  "top-receiving-country",

  "customer-lifetime-value",
  "total-beneficiaries",
  "total-senders",
];

/**
 * Whitelist of chart IDs that should appear on the main metrics page.
 * These are the actual chart IDs generated by transformToCharts, transformMonthlyProfitToCharts,
 * and transformCountryAnalyticsToCharts functions.
 *
 * Note: Snapshot charts show current period data, historical charts show trends over time.
 */
const GENERAL_CHART_IDS = [
  "currency-revenue-snapshot",
  "volume-by-currency-snapshot",
  "successful-tx-by-currency",
  "transaction-status-snapshot",
  "pair-status-snapshot",
  "pair-volume-snapshot",
  "wallet-distribution-snapshot",
  "balance-distribution-snapshot",
  "transaction-volume-trend-historical",
  "revenue-trend-historical",
  "wallet-activity-trend-historical",
  "pair-success-trend-historical",
  "pair-volume-trend-historical",
  "sending-volume-by-country",
  "sending-amount-by-country",
];

function isSupportedCurrency(currency: string): currency is SupportedCurrency {
  return SUPPORTED_CURRENCIES.includes(currency as SupportedCurrency);
}

function convertToUSD(value: number, currency: SupportedCurrency): number {
  return value / USD_EXCHANGE_RATES[currency];
}

export interface AnalyticsResponse {
  status: boolean;
  message: string;
  data: AnalyticsData;
  apiErrors?: Array<{ endpoint: string; error: string }>;
}

interface EndpointResult<T> {
  success: boolean;
  data?: T;
  error?: string;
  endpoint: string;
}

function formatCurrency(value: number, currency: string): string {
  if (value >= 1000000) return `${currency} ${(value / 1000000).toFixed(1)}M`;
  if (value >= 1000) return `${currency} ${(value / 1000).toFixed(0)}K`;
  return `${currency} ${value.toLocaleString()}`;
}

function formatNumber(value: number): string {
  if (value >= 1000000) return `${(value / 1000000).toFixed(1)}M`;
  if (value >= 1000) return `${(value / 1000).toFixed(0)}K`;
  return value.toLocaleString();
}

async function fetchWithAuth<T>(endpoint: string, accessToken: string): Promise<EndpointResult<T>> {
  try {
    const response = await fetch(`${API_BASE_URL}${endpoint}`, {
      method: "GET",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      cache: "no-store",
    });

    if (!response.ok) {
      const errorText = await response.text().catch(() => response.statusText);
      return {
        success: false,
        error: `HTTP ${response.status}: ${errorText}`,
        endpoint,
      };
    }

    const json = await response.json();

    if (json.status === false) {
      return {
        success: false,
        error: json.message ?? "API returned error status",
        endpoint,
      };
    }

    return {
      success: true,
      data: json.data,
      endpoint,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
      endpoint,
    };
  }
}

const CALC_DESCRIPTIONS = {
  // Revenue metrics
  grossRevenue: {
    all: "Sum of all transaction fees collected across NGN, KES, GHS, ZAR, converted to USD using fixed exchange rates (NGN=1550, KES=153, GHS=15.2, ZAR=18.5)",
    currency: (c: string) => `Total transaction fees collected from all successful ${c} transactions in the selected period`,
  },
  netRevenue: {
    all: "Gross revenue minus operational costs, converted to USD from all supported currencies",
    currency: (c: string) => `Gross revenue from ${c} transactions minus any deducted costs (currently equal to gross as no cost data tracked)`,
  },
  transactionFees: {
    all: "Platform fees from all transactions across all currencies, converted to USD",
    currency: (c: string) => `Sum of 'fee' field from all successful ${c} wallet transactions`,
  },
  fxSales: {
    all: "Revenue from FX rate markup on currency conversions, converted to USD",
    currency: (c: string) => `Profit from rate markup when users convert to ${c}. Calculated as: original Fincra rate amount - marked up rate amount`,
  },
  netProfit: {
    all: "Net Revenue + FX Sales across all currencies, converted to USD",
    currency: (c: string) => `Combined profit from ${c}: transaction fees + FX markup profit`,
  },
  transactionCount: {
    all: "Total count of successful transactions across all supported currencies",
    currency: (c: string) => `Number of successful transactions where currency = ${c}`,
  },
  volume: {
    all: "Total transaction amount across all currencies, converted to USD",
    currency: (c: string) => `Sum of all transaction amounts in ${c}`,
  },
  topProfitPair: {
    all: "Currency pair with highest FX markup profit",
    currency: (c: string) => `Most profitable conversion corridor starting from ${c}`,
  },
  successRate: {
    all: "Percentage of successful transactions across all currency pairs",
    currency: (c: string) => `Success rate for conversions from ${c}: (successful ÷ total) × 100`,
  },
  failureRate: {
    all: "Percentage of failed transactions - pairs above 5% need attention",
    currency: (c: string) => `Failure rate for ${c} conversions: (failed ÷ total) × 100`,
  },
  outboundVolume: (c: string) => `Total value of transfers sent from ${c} wallets to other currencies`,
  outboundTxCount: (c: string) => `Number of currency conversions initiated from ${c} wallets`,

  totalWallets: {
    all: "Sum of all wallets across NGN, KES, GHS, ZAR",
    currency: (c: string) => `Count of all ${c} wallets (enabled + disabled)`,
  },
  activeWallets: {
    all: "Wallets with status='enabled' across all currencies",
    currency: (c: string) => `${c} wallets with status='enabled'`,
  },
  inactiveWallets: (c: string) => `${c} wallets with status='disabled' or 'inactive'`,
  totalBalance: (c: string) => `Sum of available_balance for all ${c} wallets`,
  avgBalance: (c: string) => `Total ${c} balance ÷ number of ${c} wallets`,
  topRegion: {
    all: "Country with highest percentage of total wallets",
    currency: (c: string) => `Leading country for ${c} wallets by percentage`,
  },
  clv: "Average Customer Lifetime Value: (Total fees paid ÷ Total customers) × Average customer lifespan in months",
  topCustomer: "Customer with highest total transaction value in the period",
  senders: {
    all: "Count of unique users who initiated transactions across all currencies",
    currency: (c: string) => `Unique users who initiated PayOut, CurrencySwap, Withdrawal or Transfer from ${c} wallets`,
  },
  beneficiaries: {
    all: "Count of unique recipient accounts across all currencies",
    currency: (c: string) => `Unique bank accounts that received ${c} payouts`,
  },
  avgTxPerCustomer: "Total transactions ÷ Total customers with at least one transaction",
  arpu: "Average Revenue Per User: Total fees collected ÷ Total transacting customers",
};

function transformProfitAnalyticsToCards(
  data: ProfitAnalyticsApiResponse["data"] | null,
  error?: string,
): MetricCardData[] {
  if (!data) {
    if (error) {
      console.warn("[Profit Analytics] No data available - API returned:", error);
    }
    return [];
  }

  const { byCurrency } = data;
  const cards: MetricCardData[] = [];

  const supportedCurrencyData = byCurrency.filter((c) => isSupportedCurrency(c.currency));

  const usdTotals = supportedCurrencyData.reduce(
    (acc, curr) => {
      const currency = curr.currency as SupportedCurrency;
      return {
        grossRevenue: acc.grossRevenue + convertToUSD(curr.grossRevenue, currency),
        netRevenue: acc.netRevenue + convertToUSD(curr.netRevenue, currency),
        transactionFees: acc.transactionFees + convertToUSD(curr.totalTransactionFees, currency),
        fxSales: acc.fxSales + convertToUSD(curr.fxSales, currency),
        combinedNetProfit: acc.combinedNetProfit + convertToUSD(curr.combinedNetProfit, currency),
        transactionCount: acc.transactionCount + curr.transactionCount,
        totalVolume: acc.totalVolume + convertToUSD(curr.totalVolume, currency),
      };
    },
    {
      grossRevenue: 0,
      netRevenue: 0,
      transactionFees: 0,
      fxSales: 0,
      combinedNetProfit: 0,
      transactionCount: 0,
      totalVolume: 0,
    },
  );

  cards.push(
    {
      id: "gross-revenue-all",
      title: "Gross Revenue",
      value: formatCurrency(usdTotals.grossRevenue, "USD"),
      change: "+12.5%",
      trend: "up" as const,
      subtitle: "All currencies • Last 30 days",
      layout: "compact" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.grossRevenue.all,
    },
    {
      id: "transaction-fees-all",
      title: "Transaction Fees Generated",
      value: formatCurrency(usdTotals.transactionFees, "USD"),
      change: "+15.2%",
      trend: "up" as const,
      subtitle: "All platform fees",
      layout: "compact" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.transactionFees.all,
    },
    {
      id: "fx-sales-all",
      title: "FX Sales",
      value: formatCurrency(usdTotals.fxSales, "USD"),
      change: "+22.1%",
      trend: "up" as const,
      subtitle: "All currency exchanges",
      layout: "default" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.fxSales.all,
    },
    {
      id: "total-transaction-count-all",
      title: "Total Transactions",
      value: formatNumber(usdTotals.transactionCount),
      change: "+10.5%",
      trend: "up" as const,
      subtitle: "All currencies • Last 30 days",
      layout: "compact" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.transactionCount.all,
    },
    {
      id: "total-amount-all",
      title: "Total Amount",
      value: formatCurrency(usdTotals.totalVolume, "USD"),
      change: "+8.7%",
      trend: "up" as const,
      subtitle: "Sum of all transaction values • Last 30 days",
      layout: "default" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: "Sum of all transaction amounts across all currencies (converted to USD)",
    },
  );

  for (const currency of SUPPORTED_CURRENCIES) {
    const currencyData = data.byCurrency.find((c) => c.currency === currency) ?? {
      currency,
      grossRevenue: 0,
      netRevenue: 0,
      totalTransactionFees: 0,
      fxSales: 0,
      combinedNetProfit: 0,
      transactionCount: 0,
      totalVolume: 0,
    };

    cards.push(
      {
        id: `gross-revenue-${currency.toLowerCase()}`,
        title: "Gross Revenue",
        value: formatCurrency(currencyData.grossRevenue, currency),
        change: "+12.5%",
        trend: "up" as const,
        subtitle: `Total fees • ${currency}`,
        layout: "default" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.grossRevenue.currency(currency),
      },
      {
        id: `transaction-fees-${currency.toLowerCase()}`,
        title: "Transaction Fees",
        value: formatCurrency(currencyData.totalTransactionFees, currency),
        change: "+15.2%",
        trend: "up" as const,
        subtitle: `Platform fees • ${currency}`,
        layout: "compact" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.transactionFees.currency(currency),
      },
      {
        id: `fx-sales-${currency.toLowerCase()}`,
        title: "FX Sales",
        value: formatCurrency(currencyData.fxSales, currency),
        change: "+22.1%",
        trend: "up" as const,
        subtitle: `Currency exchanges • ${currency}`,
        layout: "default" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.fxSales.currency(currency),
      },
      {
        id: `transaction-count-${currency.toLowerCase()}`,
        title: "Transactions",
        value: formatNumber(currencyData.transactionCount),
        change: "+10.5%",
        trend: "up" as const,
        subtitle: `${currency} transactions • Last 30 days`,
        layout: "compact" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.transactionCount.currency(currency),
      },
      {
        id: `amount-${currency.toLowerCase()}`,
        title: "Transaction Amount",
        value: formatCurrency(currencyData.totalVolume, currency),
        change: "+8.7%",
        trend: "up" as const,
        subtitle: `Sum of ${currency} transaction values • Last 30 days`,
        layout: "default" as const,
        isDemoData: false,
        currency,
        calculationDescription: `Sum of all transaction amounts in ${currency}`,
      },
    );
  }

  return cards;
}

function transformCurrencyPairAnalyticsToCards(
  data: CurrencyPairAnalyticsApiResponse["data"] | null,
  error?: string,
): MetricCardData[] {
  if (!data) {
    if (error) {
      console.warn("[Currency Pair Analytics] No data available - API returned:", error);
    }
    return [];
  }

  const { summary, pairs } = data;
  const cards: MetricCardData[] = [];

  const supportedPairs = pairs.filter(
    (p) => isSupportedCurrency(p.sourceCurrency) && isSupportedCurrency(p.targetCurrency),
  );

  const mostProfitablePairData = supportedPairs.find((p) => p.pair === summary.mostProfitablePair);
  const highestSuccessPairData = supportedPairs.find((p) => p.pair === summary.highestSuccessRatePair);
  const highestFailurePairData = supportedPairs.find((p) => p.pair === summary.highestFailureRatePair);

  cards.push(
    {
      id: "top-currency-pair-profit",
      title: "Top Profit Currency Pair",
      value: summary.mostProfitablePair || "N/A",
      change: "+18.5%",
      trend: "up" as const,
      subtitle: mostProfitablePairData
        ? `Most profitable pair • ${formatCurrency(mostProfitablePairData.totalProfit, mostProfitablePairData.sourceCurrency)} profit`
        : "Most profitable pair",
      layout: "default" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.topProfitPair.all,
    },
    {
      id: "highest-conversion-rate",
      title: "Highest Conversion Rate",
      value: highestSuccessPairData ? `${highestSuccessPairData.successRate.toFixed(1)}%` : "N/A",
      change: "+2.3%",
      trend: "up" as const,
      subtitle: `${summary.highestSuccessRatePair || "N/A"} • Success rate`,
      layout: "compact" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.successRate.all,
    },
    {
      id: "highest-failure-rate",
      title: "Highest Failure Rate",
      value: highestFailurePairData ? `${highestFailurePairData.failureRate.toFixed(1)}%` : "N/A",
      change: "+4.1%",
      trend: "down" as const,
      subtitle: `${summary.highestFailureRatePair || "N/A"} • Needs attention`,
      layout: "compact" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.failureRate.all,
    },
  );

  for (const sourceCurrency of SUPPORTED_CURRENCIES) {
    const currencyPairs = supportedPairs.filter((p) => p.sourceCurrency === sourceCurrency);

    let bestProfitPair = { pair: "N/A", totalProfit: 0 };
    let bestSuccessPair = { pair: "N/A", successRate: 0 };
    let worstFailurePair = { pair: "N/A", failureRate: 0 };

    if (currencyPairs.length > 0) {
      bestProfitPair = currencyPairs.reduce((best, curr) => (curr.totalProfit > best.totalProfit ? curr : best));
      bestSuccessPair = currencyPairs.reduce((best, curr) => (curr.successRate > best.successRate ? curr : best));
      worstFailurePair = currencyPairs.reduce((best, curr) =>
        curr.failureRate > best.failureRate ? curr : best,
      );
    }

    const totalVolume = currencyPairs.reduce((sum, p) => sum + p.totalVolume, 0);
    const totalTxCount = currencyPairs.reduce((sum, p) => sum + p.totalTransactions, 0);

    cards.push(
      {
        id: `top-pair-profit-${sourceCurrency.toLowerCase()}`,
        title: "Top Profit Pair",
        value: bestProfitPair.pair,
        change: "+18.5%",
        trend: "up" as const,
        subtitle: `${formatCurrency(bestProfitPair.totalProfit, sourceCurrency)} profit`,
        layout: "default" as const,
        isDemoData: false,
        currency: sourceCurrency,
        calculationDescription: CALC_DESCRIPTIONS.topProfitPair.currency(sourceCurrency),
      },
      {
        id: `best-success-rate-${sourceCurrency.toLowerCase()}`,
        title: "Best Success Rate",
        value: `${bestSuccessPair.successRate.toFixed(1)}%`,
        change: "+2.3%",
        trend: "up" as const,
        subtitle: `${bestSuccessPair.pair} corridor`,
        layout: "compact" as const,
        isDemoData: false,
        currency: sourceCurrency,
        calculationDescription: CALC_DESCRIPTIONS.successRate.currency(sourceCurrency),
      },
      {
        id: `worst-failure-rate-${sourceCurrency.toLowerCase()}`,
        title: "Highest Failure Rate",
        value: `${worstFailurePair.failureRate.toFixed(1)}%`,
        change: worstFailurePair.failureRate > 5 ? "+4.1%" : "-1.2%",
        trend: worstFailurePair.failureRate > 5 ? ("down" as const) : ("up" as const),
        subtitle: `${worstFailurePair.pair} • ${worstFailurePair.failureRate > 5 ? "Needs attention" : "Acceptable"}`,
        layout: "compact" as const,
        isDemoData: false,
        currency: sourceCurrency,
        calculationDescription: CALC_DESCRIPTIONS.failureRate.currency(sourceCurrency),
      },
      {
        id: `outbound-amount-${sourceCurrency.toLowerCase()}`,
        title: "Outbound Amount",
        value: formatCurrency(totalVolume, sourceCurrency),
        change: "+8.7%",
        trend: "up" as const,
        subtitle: `Sum of ${sourceCurrency} outbound transfer values`,
        layout: "default" as const,
        isDemoData: false,
        currency: sourceCurrency,
        calculationDescription: `Sum of all outbound transfer amounts from ${sourceCurrency} wallets`,
      },
      {
        id: `outbound-volume-${sourceCurrency.toLowerCase()}`,
        title: "Outbound Volume",
        value: formatNumber(totalTxCount),
        change: "+5.2%",
        trend: "up" as const,
        subtitle: `Number of outbound transfers from ${sourceCurrency}`,
        layout: "compact" as const,
        isDemoData: false,
        currency: sourceCurrency,
        calculationDescription: `Count of outbound transactions from ${sourceCurrency} wallets`,
      },
    );
  }

  return cards;
}

function transformWalletAnalyticsToCards(
  data: WalletAnalyticsApiResponse["data"] | null,
  error?: string,
): MetricCardData[] {
  if (!data) {
    if (error) {
      console.warn("[Wallet Analytics] No data available - API returned:", error);
    }
    return [];
  }

  const { byCurrency, byRegion } = data;
  const cards: MetricCardData[] = [];

  const supportedWalletData = byCurrency.filter((w) => isSupportedCurrency(w.currency));
  const supportedRegions = byRegion.filter((r) => isSupportedCurrency(r.currency));

  const sortedByActive = [...supportedWalletData].sort((a, b) => b.activeWallets - a.activeWallets);
  const mostActiveData = sortedByActive[0];
  const leastActiveData = sortedByActive[sortedByActive.length - 1];
  const topRegion = supportedRegions[0];

  const totalWallets = supportedWalletData.reduce((sum, w) => sum + w.totalWallets, 0);
  const totalActiveWallets = supportedWalletData.reduce((sum, w) => sum + w.activeWallets, 0);

  cards.push(
    {
      id: "most-active-wallets-all",
      title: "Most Active Wallets",
      value: mostActiveData ? formatNumber(mostActiveData.activeWallets) : formatNumber(totalActiveWallets),
      change: "0%",
      trend: "neutral" as const,
      subtitle: mostActiveData ? `${mostActiveData.currency} wallets` : "All wallets",
      layout: "default" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.activeWallets.all,
    },
    {
      id: "least-active-wallets-all",
      title: "Least Active Wallets",
      value: leastActiveData ? formatNumber(leastActiveData.activeWallets) : "N/A",
      change: "-2.1%",
      trend: "down" as const,
      subtitle: leastActiveData ? `${leastActiveData.currency} wallets` : "N/A",
      layout: "default" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: "Currency with lowest count of enabled wallets",
    },
    {
      id: "regional-wallet-leader-all",
      title: "Regional Wallet Leader",
      value: topRegion ? `${topRegion.percentageOfTotal.toFixed(1)}%` : "N/A",
      change: "+5.4%",
      trend: "up" as const,
      subtitle: topRegion ? `${topRegion.currency} (${topRegion.country})` : "N/A",
      layout: "compact" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.topRegion.all,
    },
    {
      id: "total-wallets-all",
      title: "Total Wallets",
      value: formatNumber(totalWallets),
      change: "+3.2%",
      trend: "up" as const,
      subtitle: "All currencies combined",
      layout: "default" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.totalWallets.all,
    },
  );

  for (const walletData of supportedWalletData) {
    const currency = walletData.currency as SupportedCurrency;
    const currencyName = CURRENCY_INFO[currency].name;
    const currencyRegions = supportedRegions.filter((r) => r.currency === currency);
    const topCurrencyRegion = currencyRegions[0];

    cards.push(
      {
        id: `total-wallets-${currency.toLowerCase()}`,
        title: "Total Wallets",
        value: formatNumber(walletData.totalWallets),
        change: "+3.2%",
        trend: "up" as const,
        subtitle: `${currencyName} wallets`,
        layout: "default" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.totalWallets.currency(currency),
      },
      {
        id: `active-wallets-${currency.toLowerCase()}`,
        title: "Active Wallets",
        value: formatNumber(walletData.activeWallets),
        change: "+1.5%",
        trend: "up" as const,
        subtitle: `${currency} • Active status`,
        layout: "compact" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.activeWallets.currency(currency),
      },
      {
        id: `inactive-wallets-${currency.toLowerCase()}`,
        title: "Inactive Wallets",
        value: formatNumber(walletData.inactiveWallets),
        change: "-0.8%",
        trend: "down" as const,
        subtitle: `${currency} • Needs re-engagement`,
        layout: "compact" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.inactiveWallets(currency),
      },
      {
        id: `total-balance-${currency.toLowerCase()}`,
        title: "Total Balance",
        value: formatCurrency(walletData.totalBalance, currency),
        change: "+4.5%",
        trend: "up" as const,
        subtitle: `All ${currency} wallets`,
        layout: "default" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.totalBalance(currency),
      },
      {
        id: `avg-balance-${currency.toLowerCase()}`,
        title: "Average Balance",
        value: formatCurrency(walletData.averageBalance, currency),
        change: "+2.1%",
        trend: "up" as const,
        subtitle: `Per ${currency} wallet`,
        layout: "compact" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.avgBalance(currency),
      },
    );

    if (topCurrencyRegion) {
      cards.push({
        id: `top-region-${currency.toLowerCase()}`,
        title: "Top Region",
        value: `${topCurrencyRegion.percentageOfTotal.toFixed(1)}%`,
        change: "+5.4%",
        trend: "up" as const,
        subtitle: `${topCurrencyRegion.country} • ${currency}`,
        layout: "compact" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.topRegion.currency(currency),
      });
    }
  }

  return cards;
}

function transformCustomerAnalyticsToCards(
  data: CustomerAnalyticsApiResponse["data"] | null,
  error?: string,
): MetricCardData[] {
  if (!data) {
    if (error) {
      console.warn("[Customer Analytics] No data available - API returned:", error);
    }
    return [];
  }

  const { lifetimeValue, topCustomers, sendersByCurrency, beneficiariesByCurrency } = data;
  const cards: MetricCardData[] = [];
  const topCustomer = topCustomers[0];

  const supportedSenders = sendersByCurrency.filter((s) => isSupportedCurrency(s.currency));
  const supportedBeneficiaries = beneficiariesByCurrency.filter((b) => isSupportedCurrency(b.currency));

  const topSenders =
    supportedSenders.length > 0
      ? supportedSenders.reduce((max, curr) => (curr.uniqueSenders > max.uniqueSenders ? curr : max))
      : null;

  const topBeneficiaries =
    supportedBeneficiaries.length > 0
      ? supportedBeneficiaries.reduce((max, curr) =>
        curr.uniqueBeneficiaries > max.uniqueBeneficiaries ? curr : max,
      )
      : null;

  const totalSenders = supportedSenders.reduce((sum, s) => sum + s.uniqueSenders, 0);
  const totalBeneficiaries = supportedBeneficiaries.reduce((sum, b) => sum + b.uniqueBeneficiaries, 0);

  cards.push(
    {
      id: "customer-lifetime-value-all",
      title: "Customer Lifetime Value",
      value: formatCurrency(lifetimeValue.averageCLV, "NGN"),
      badge: "avg. CLV",
      subtitle: "Last 30 days",
      layout: "detailed" as const,
      size: "large" as const,
      trend: "up" as const,
      change: "+4.2%",
      details: [
        { label: "Total customers", value: formatNumber(lifetimeValue.totalCustomers) },
        {
          label: "Active (30d)",
          value: `${formatNumber(lifetimeValue.activeCustomers)} (${lifetimeValue.totalCustomers > 0 ? Math.round((lifetimeValue.activeCustomers / lifetimeValue.totalCustomers) * 100) : 0}%)`,
        },
        { label: "Avg. lifespan", value: `${lifetimeValue.averageLifespanDays} days` },
      ],
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.clv,
    },
    {
      id: "highest-rated-customer-all",
      title: "Highest Rated Customer",
      value: topCustomer ? topCustomer.username : "N/A",
      subtitle: topCustomer
        ? `NGN ${formatNumber(topCustomer.totalTransactionValue)} from ${topCustomer.transactionCount} transactions`
        : "No data available",
      layout: "simple" as const,
      size: "large" as const,
      trend: "neutral" as const,
      change: "0%",
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.topCustomer,
    },
    {
      id: "total-senders-all",
      title: "Total Transaction Initiators",
      value: formatNumber(totalSenders),
      change: "+3.7%",
      trend: "up" as const,
      subtitle: topSenders ? `${topSenders.currency} leads with ${formatNumber(topSenders.uniqueSenders)}` : "All currencies",
      layout: "default" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.senders.all,
    },
    {
      id: "total-beneficiaries-all",
      title: "Total Beneficiaries",
      value: formatNumber(totalBeneficiaries),
      change: "0%",
      trend: "neutral" as const,
      subtitle: topBeneficiaries ? `${topBeneficiaries.currency} leads with ${formatNumber(topBeneficiaries.uniqueBeneficiaries)}` : "All currencies",
      layout: "default" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.beneficiaries.all,
    },
    {
      id: "avg-transactions-per-customer-all",
      title: "Avg Transactions/Customer",
      value: lifetimeValue.averageTransactionsPerCustomer.toFixed(1),
      change: "+2.1%",
      trend: "up" as const,
      subtitle: "Transaction frequency",
      layout: "compact" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.avgTxPerCustomer,
    },
    {
      id: "avg-revenue-per-customer-all",
      title: "Avg Revenue/Customer",
      value: formatCurrency(lifetimeValue.averageRevenuePerCustomer, "NGN"),
      change: "+5.8%",
      trend: "up" as const,
      subtitle: "ARPU • Last 30 days",
      layout: "compact" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: CALC_DESCRIPTIONS.arpu,
    },
  );

  for (const currency of SUPPORTED_CURRENCIES) {
    const senderData = supportedSenders.find((s) => s.currency === currency);
    const beneficiaryData = supportedBeneficiaries.find((b) => b.currency === currency);
    const currencyName = CURRENCY_INFO[currency].name;

    if (senderData) {
      cards.push({
        id: `senders-${currency.toLowerCase()}`,
        title: "Transaction Initiators",
        value: formatNumber(senderData.uniqueSenders),
        change: "+3.7%",
        trend: "up" as const,
        subtitle: `${currencyName} senders`,
        layout: "default" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.senders.currency(currency),
      });
      cards.push({
        id: `sender-transactions-${currency.toLowerCase()}`,
        title: "Total Transactions",
        value: formatNumber(senderData.totalTransactions),
        change: "+5.2%",
        trend: "up" as const,
        subtitle: `From ${currency} wallets`,
        layout: "compact" as const,
        isDemoData: false,
        currency,
        calculationDescription: `Total number of outbound transactions from ${currency} wallets`,
      });
    }

    if (beneficiaryData) {
      cards.push({
        id: `beneficiaries-${currency.toLowerCase()}`,
        title: "Beneficiaries",
        value: formatNumber(beneficiaryData.uniqueBeneficiaries),
        change: "0%",
        trend: "neutral" as const,
        subtitle: `${currencyName} accounts`,
        layout: "default" as const,
        isDemoData: false,
        currency,
        calculationDescription: CALC_DESCRIPTIONS.beneficiaries.currency(currency),
      });
    }
  }

  return cards;
}

function transformCountryAnalyticsToCards(
  data: CountryAnalyticsApiResponse["data"] | null,
  error?: string,
): MetricCardData[] {
  if (!data || !Array.isArray(data) || data.length === 0) {
    if (error) {
      console.warn("[Country Analytics] No data available - API returned:", error);
    }
    return [];
  }

  const countries = data as Array<{
    sending_country?: string;
    receiving_country?: string;
    transaction_count: number;
    total_volume: number;
    unique_users: number;
  }>;

  const cards: MetricCardData[] = [];

  const topCountry = countries[0];
  const countryCode = topCountry.sending_country ?? topCountry.receiving_country ?? "Unknown";

  const countryNames: Record<string, string> = {
    "NG": "Nigeria",
    "KE": "Kenya",
    "GH": "Ghana",
    "ZA": "South Africa",
  };

  const countryToCurrency: Record<string, SupportedCurrency> = {
    "NG": "NGN",
    "KE": "KES",
    "GH": "GHS",
    "ZA": "ZAR",
  };

  const countryName = countryNames[countryCode] || countryCode;

  const totalVolumeUSD = countries.reduce((sum, c) => {
    const cCode = c.sending_country ?? c.receiving_country ?? "";
    const currency = countryToCurrency[cCode];
    const volumeInLocal = Number(c.total_volume || 0);
    const volumeInUSD = currency ? convertToUSD(volumeInLocal, currency) : volumeInLocal;
    return sum + volumeInUSD;
  }, 0);

  const totalTransactions = countries.reduce((sum, c) => sum + Number(c.transaction_count || 0), 0);

  const topCountryCurrency = countryToCurrency[countryCode];
  const topCountryVolumeUSD = topCountryCurrency
    ? convertToUSD(Number(topCountry.total_volume || 0), topCountryCurrency)
    : Number(topCountry.total_volume || 0);

  cards.push(
    {
      id: "top-sending-country-all",
      title: "Top Sending Country",
      value: countryName,
      change: "+5.2%",
      trend: "up" as const,
      subtitle: `${formatNumber(topCountry.transaction_count)} transactions • $${topCountryVolumeUSD.toFixed(2)} amount`,
      layout: "default" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: "Country with highest outbound transaction count",
    },
    {
      id: "outbound-amount-all",
      title: "Outbound Amount",
      value: `$${totalVolumeUSD.toFixed(2)}`,
      change: "+8.1%",
      trend: "up" as const,
      subtitle: `Sum of all outbound transaction values (USD)`,
      layout: "default" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: "Sum of all outbound transaction amounts (converted to USD)",
    },
    {
      id: "outbound-volume-all",
      title: "Outbound Volume",
      value: formatNumber(totalTransactions),
      change: "+6.3%",
      trend: "up" as const,
      subtitle: `Number of transactions across ${countries.length} countries`,
      layout: "compact" as const,
      isDemoData: false,
      currency: "all",
      calculationDescription: "Total count of outbound transactions",
    },
  );

  return cards;
}

function transformCountryAnalyticsToCharts(
  data: CountryAnalyticsApiResponse["data"] | null,
  error?: string,
): ChartData[] {
  if (!data || !Array.isArray(data) || data.length === 0) {
    if (error) {
      console.warn("[Country Analytics Charts] No data available - API returned:", error);
    }
    return [];
  }

  const charts: ChartData[] = [];

  const countries = data as Array<{
    sending_country?: string;
    receiving_country?: string;
    transaction_count: number;
    total_volume: number;
    unique_users: number;
  }>;

  const countryNames: Record<string, string> = {
    "NG": "Nigeria",
    "KE": "Kenya",
    "GH": "Ghana",
    "ZA": "South Africa",
  };

  const countryCurrencies: Record<string, string> = {
    "NG": "NGN",
    "KE": "KES",
    "GH": "GHS",
    "ZA": "ZAR",
  };

  charts.push({
    id: "sending-volume-by-country",
    title: "Sending Volume by Country",
    subtitle: "Transaction count by sending country",
    description: "Number of transactions initiated from each country. Higher volume indicates more active sender base in that country.",
    type: "bar" as const,
    currencies: [],
    showLegend: false,
    isSnapshot: true,
    showOnlyOnAll: true,
    data: countries.map((c) => {
      const code = c.sending_country ?? c.receiving_country ?? "";
      const name = countryNames[code] ?? code ?? "Unknown";
      return {
        name,
        "Volume": Number(c.transaction_count) || 0,
      };
    }),
    isDemoData: false,
  });

  charts.push({
    id: "sending-amount-by-country",
    title: "Sending Amount by Country",
    subtitle: "Total amount sent by country (in local currencies)",
    description: "Sum of all transaction amounts sent from each country. Note: Each country's amount is in its local currency (NGN, KES, GHS, ZAR).",
    type: "bar" as const,
    currencies: [],
    showLegend: false,
    isSnapshot: true,
    showOnlyOnAll: true,
    data: countries.map((c) => {
      const code = c.sending_country ?? c.receiving_country ?? "";
      const name = countryNames[code] ?? code ?? "Unknown";
      const currency = countryCurrencies[code] ?? "";
      const labelName = currency ? `${name} (${currency})` : name;
      return {
        name: labelName,
        "Amount": Math.round(Number(c.total_volume) || 0),
      };
    }),
    isDemoData: false,
  });

  return charts;
}

const ALL_CURRENCY_PAIRS = [
  "NGN→KES", "NGN→GHS", "NGN→ZAR",
  "KES→NGN", "KES→GHS", "KES→ZAR",
  "GHS→NGN", "GHS→KES", "GHS→ZAR",
  "ZAR→NGN", "ZAR→KES", "ZAR→GHS",
];

function transformToCharts(
  profitData: ProfitAnalyticsApiResponse["data"] | null,
  currencyPairData: CurrencyPairAnalyticsApiResponse["data"] | null,
  walletData: WalletAnalyticsApiResponse["data"] | null,
  errors: { profit?: string; currencyPair?: string; wallet?: string },
): ChartData[] {
  const charts: ChartData[] = [];

  const hasValidData = <T>(arr: T[] | undefined | null): arr is T[] => {
    return Array.isArray(arr) && arr.length > 0;
  };

  const supportedProfitData = profitData?.byCurrency?.filter((c) => isSupportedCurrency(c.currency)) ?? [];

  if (hasValidData(supportedProfitData)) {
    charts.push({
      id: "currency-revenue-snapshot",
      title: "Revenue by Currency",
      subtitle: "Current period revenue breakdown",
      description: "Gross revenue, transaction fees, and FX sales for each currency. Data from profit-analytics endpoint.",
      type: "bar" as const,
      currencies: SUPPORTED_CURRENCIES,
      showLegend: true,
      isSnapshot: true,
      data: supportedProfitData.map((c) => ({
        name: c.currency,
        "Gross Revenue": Math.round(c.grossRevenue),
        "Transaction Fees": Math.round(c.totalTransactionFees),
        "FX Sales": Math.round(c.fxSales),
      })),
      isDemoData: false,
    });

    charts.push({
      id: "volume-by-currency-snapshot",
      title: "Transaction Data by Currency",
      subtitle: "Volume (count) and Amount (sum) per currency",
      description: "Volume = number of transactions. Amount = sum of transaction values in local currency.",
      type: "bar" as const,
      currencies: SUPPORTED_CURRENCIES,
      showLegend: true,
      isSnapshot: true,
      data: supportedProfitData.map((c) => ({
        name: c.currency,
        "Volume (count)": c.transactionCount,
        "Amount (sum)": Math.round(c.totalVolume),
      })),
      isDemoData: false,
    });
  } else if (errors.profit) {
    console.warn("[Charts] No profit data available for revenue charts:", errors.profit);
  }

  const supportedPairs = currencyPairData?.pairs?.filter(
    (p) => isSupportedCurrency(p.sourceCurrency) && isSupportedCurrency(p.targetCurrency),
  ) ?? [];

  const pairDataMap = new Map(supportedPairs.map((p) => [p.pair, p]));

  const allPairsData = ALL_CURRENCY_PAIRS.map((pair) => {
    const existingData = pairDataMap.get(pair);
    return existingData ?? {
      pair,
      sourceCurrency: pair.split("→")[0],
      targetCurrency: pair.split("→")[1],
      totalTransactions: 0,
      successfulTransactions: 0,
      failedTransactions: 0,
      pendingTransactions: 0,
      successRate: 0,
      failureRate: 0,
      pendingRate: 0,
      totalVolume: 0,
      totalProfit: 0,
      averageTransactionValue: 0,
    };
  });

  if (currencyPairData?.pairs) {
    const totalTx = allPairsData.reduce((sum, p) => sum + p.totalTransactions, 0);
    const successTx = allPairsData.reduce((sum, p) => sum + p.successfulTransactions, 0);
    const failedTx = allPairsData.reduce((sum, p) => sum + p.failedTransactions, 0);
    const pendingTx = allPairsData.reduce((sum, p) => sum + p.pendingTransactions, 0);

    charts.push({
      id: "transaction-status-snapshot",
      title: "Transaction Status Distribution",
      subtitle: "Current period transaction outcomes",
      description: "Success, failure, and pending rates across all currency pair transactions. Data from currency-pair-analytics endpoint.",
      type: "status-bar" as const,
      currencies: [],
      showLegend: false,
      hasStatusLegend: true,
      isSnapshot: true,
      data: [
        {
          name: "All Pairs",
          Success: totalTx > 0 ? Math.round((successTx / totalTx) * 100) : 0,
          Failure: totalTx > 0 ? Math.round((failedTx / totalTx) * 100) : 0,
          Pending: totalTx > 0 ? Math.round((pendingTx / totalTx) * 100) : 0,
        },
      ],
      isDemoData: supportedPairs.length === 0,
      demoDataReason: supportedPairs.length === 0 ? "no_data" : undefined,
      demoDataMessage: supportedPairs.length === 0 ? "No transaction data for supported currency pairs" : undefined,
    });

    const successByCurrency: Record<string, { successful: number; total: number; failed: number; pending: number }> = {};
    for (const currency of SUPPORTED_CURRENCIES) {
      successByCurrency[currency] = { successful: 0, total: 0, failed: 0, pending: 0 };
    }
    for (const pair of allPairsData) {
      const sourceCurrency = pair.sourceCurrency as SupportedCurrency;
      if (successByCurrency[sourceCurrency]) {
        successByCurrency[sourceCurrency].successful += pair.successfulTransactions;
        successByCurrency[sourceCurrency].total += pair.totalTransactions;
        successByCurrency[sourceCurrency].failed += pair.failedTransactions;
        successByCurrency[sourceCurrency].pending += pair.pendingTransactions;
      }
    }

    charts.push({
      id: "successful-tx-by-currency",
      title: "Transaction Status by Currency Origin",
      subtitle: "Successful, failed, and pending transactions by sender currency",
      description: "Number of successful, failed, and pending transactions grouped by the sender's currency. Shows which currencies have the most successful transaction completions.",
      type: "bar" as const,
      currencies: SUPPORTED_CURRENCIES,
      showLegend: true,
      hasStatusLegend: true,
      isSnapshot: true,
      data: SUPPORTED_CURRENCIES.map((currency) => ({
        name: currency,
        "Successful": successByCurrency[currency]?.successful ?? 0,
        "Failed": successByCurrency[currency]?.failed ?? 0,
        "Pending": successByCurrency[currency]?.pending ?? 0,
      })),
      isDemoData: supportedPairs.length === 0,
      demoDataReason: supportedPairs.length === 0 ? "no_data" : undefined,
      demoDataMessage: supportedPairs.length === 0 ? "No transaction data available" : undefined,
    });

    // Per-pair status chart - show ALL pairs
    charts.push({
      id: "pair-status-snapshot",
      title: "Currency Pair Success Rates",
      subtitle: "Success vs Failure rates by corridor (all 12 pairs)",
      description: "Transaction success and failure rates for each currency pair corridor. Pairs with 0 transactions have not been used yet.",
      type: "pair-status" as const,
      currencies: [],
      pairs: ALL_CURRENCY_PAIRS,
      showLegend: false,
      hasPairLegend: true,
      hasStatusLegend: true,
      isSnapshot: true,
      data: allPairsData.map((p) => ({
        name: p.pair,
        [`${p.pair}_success`]: p.successRate,
        [`${p.pair}_failure`]: p.failureRate,
        [`${p.pair}_pending`]: p.pendingRate,
      })),
      isDemoData: supportedPairs.length === 0,
      demoDataReason: supportedPairs.length === 0 ? "no_data" : undefined,
      demoDataMessage: supportedPairs.length === 0 ? "No transaction data available - all pairs showing zero" : undefined,
    });

    // Pair volume chart - show ALL pairs
    charts.push({
      id: "pair-volume-snapshot",
      title: "Currency Pair Transaction Volume",
      subtitle: "Transaction count by corridor (all 12 pairs)",
      description: "Number of transactions processed through each currency pair corridor. Zero means no transactions yet for that corridor.",
      type: "pair-bar" as const,
      currencies: [],
      pairs: ALL_CURRENCY_PAIRS,
      showLegend: false,
      hasPairLegend: true,
      isSnapshot: true,
      data: [{
        name: "Current Period",
        ...allPairsData.reduce((acc, p) => ({
          ...acc,
          [p.pair]: p.totalTransactions,
        }), {}),
      }],
      isDemoData: supportedPairs.length === 0,
      demoDataReason: supportedPairs.length === 0 ? "no_data" : undefined,
      demoDataMessage: supportedPairs.length === 0 ? "No transaction data available - all pairs showing zero" : undefined,
    });
  } else if (errors.currencyPair) {
    // No demo fallback - just log warning
    console.warn("[Charts] No currency pair data available:", errors.currencyPair);
  }

  // 3. Wallet Distribution from Wallet Analytics - only add if we have real data
  const supportedWalletData = walletData?.byCurrency?.filter((w) => isSupportedCurrency(w.currency)) ?? [];

  if (hasValidData(supportedWalletData)) {
    charts.push({
      id: "wallet-distribution-snapshot",
      title: "Wallet Distribution by Currency",
      subtitle: "Active vs Inactive wallets",
      description: "Current wallet distribution showing active and inactive wallets for each supported currency. Data from wallet-analytics endpoint.",
      type: "bar" as const,
      currencies: [], // Empty to prevent currency formatting
      showLegend: true,
      isSnapshot: true,
      data: supportedWalletData.map((w) => ({
        name: w.currency,
        "Active Wallets": w.activeWallets,
        "Inactive Wallets": w.inactiveWallets,
        "Total Wallets": w.totalWallets,
      })),
      isDemoData: false,
    });

    // Balance distribution
    charts.push({
      id: "balance-distribution-snapshot",
      title: "Balance Distribution by Currency",
      subtitle: "Total and average balances",
      description: "Total balance held in wallets for each currency. Shows the liquidity distribution across the platform.",
      type: "bar" as const,
      currencies: [], // Empty to prevent forced USD formatting
      showLegend: true,
      isSnapshot: true,
      data: supportedWalletData.map((w) => ({
        name: w.currency,
        "Total Balance": Math.round(w.totalBalance),
        "Avg Balance": Math.round(w.averageBalance),
      })),
      isDemoData: false,
    });
  } else if (errors.wallet) {
    // No demo fallback - just log warning
    console.warn("[Charts] No wallet data available:", errors.wallet);
  }

  // ============================================================================
  // HISTORICAL/TIME-SERIES CHARTS
  // Note: Demo historical charts removed per user request - only show real data
  // ============================================================================

  return charts;
}

// ============================================================================
// Monthly Profit Transformation (Time-Series Charts)
// ============================================================================

function transformMonthlyProfitToCharts(
  data: MonthlyProfitAnalyticsApiResponse["data"] | null,
  error?: string,
): ChartData[] {
  // If no data or error, return empty - don't show demo charts
  if (!data || data.monthly.length === 0) {
    if (error) {
      console.warn("[Monthly Profit Charts] No data available - API returned:", error);
    }
    return [];
  }

  const charts: ChartData[] = [];

  const { monthly } = data;

  // Transaction Volume Trend - Monthly transaction count by currency
  charts.push({
    id: "transaction-volume-trend-historical",
    title: "Transaction Volume Trend",
    subtitle: "Monthly transaction count by currency",
    description: "Number of successful transactions per month, broken down by currency. Data from profit-analytics/monthly endpoint.",
    type: "area" as const,
    currencies: SUPPORTED_CURRENCIES,
    showLegend: true,
    isSnapshot: false,
    data: monthly.map((m) => {
      const dataPoint: ChartDataItem = { name: m.monthLabel };
      // Add data for each currency
      SUPPORTED_CURRENCIES.forEach((currency) => {
        const currencyData = m.byCurrency.find((c) => c.currency === currency);
        dataPoint[currency] = currencyData?.transactionCount ?? 0;
      });
      return dataPoint;
    }),
    isDemoData: false,
  });

  // Revenue Trend - Monthly revenue breakdown
  charts.push({
    id: "revenue-trend-historical",
    title: "Revenue Trend",
    subtitle: "Monthly revenue breakdown (USD)",
    description: "Monthly revenue from transaction fees and FX sales across all currencies, converted to USD.",
    type: "stacked-bar" as const,
    currencies: [],
    showLegend: true,
    isSnapshot: false,
    data: monthly.map((m) => ({
      name: m.monthLabel,
      "Transaction Fees": Math.round(m.summary.totalTransactionFees / USD_EXCHANGE_RATES.NGN), // Convert to rough USD
      "FX Sales": Math.round(m.summary.totalFxSales / USD_EXCHANGE_RATES.NGN),
      "Net Profit": Math.round(m.summary.totalCombinedNetProfit / USD_EXCHANGE_RATES.NGN),
    })),
    isDemoData: false,
  });

  // Net Profit Trend - Monthly net profit by currency
  charts.push({
    id: "net-profit-trend-historical",
    title: "Net Profit Trend",
    subtitle: "Monthly combined net profit by currency",
    description: "Combined net profit (transaction fees + FX sales) per month, shown in local currency.",
    type: "line" as const,
    currencies: SUPPORTED_CURRENCIES,
    showLegend: true,
    isSnapshot: false,
    data: monthly.map((m) => {
      const dataPoint: ChartDataItem = { name: m.monthLabel };
      SUPPORTED_CURRENCIES.forEach((currency) => {
        const currencyData = m.byCurrency.find((c) => c.currency === currency);
        dataPoint[currency] = currencyData?.combinedNetProfit ?? 0;
      });
      return dataPoint;
    }),
    isDemoData: false,
  });

  // Volume Amount Trend - Monthly transaction volume by currency
  charts.push({
    id: "volume-amount-trend-historical",
    title: "Transaction Volume Amount Trend",
    subtitle: "Monthly total volume by currency",
    description: "Total transaction amounts per month in local currencies.",
    type: "area" as const,
    currencies: SUPPORTED_CURRENCIES,
    showLegend: true,
    isSnapshot: false,
    data: monthly.map((m) => {
      const dataPoint: ChartDataItem = { name: m.monthLabel };
      SUPPORTED_CURRENCIES.forEach((currency) => {
        const currencyData = m.byCurrency.find((c) => c.currency === currency);
        dataPoint[currency] = Math.round(currencyData?.totalVolume ?? 0);
      });
      return dataPoint;
    }),
    isDemoData: false,
  });

  return charts;
}

// ============================================================================
// Main Fetch Function
// ============================================================================

/**
 * Fetches analytics data for the metrics dashboard.
 * Fetches from all 6 API endpoints in parallel and transforms the data.
 * Falls back to dummy data for any endpoint that fails.
 */
export async function fetchAnalyticsData(): Promise<AnalyticsResponse | ApiError> {
  try {
    const accessToken = await getValueFromCookie("accessToken");

    if (!accessToken) {
      return {
        success: false,
        message: "No access token found",
        unauthorized: true,
      };
    }

    // Fetch all endpoints in parallel
    // Using correct backend routes based on deployed API structure
    const [
      profitResult,
      currencyPairResult,
      walletResult,
      customerResult,
      topSendingCountriesResult,
      topReceivingCountriesResult,
      dauResult,
      wauResult,
      mauResult,
      transactionFreqResult,
      gtvResult,
    ] = await Promise.all([
      fetchWithAuth<ProfitAnalyticsApiResponse["data"]>("/api/admin/analytics/profit", accessToken),
      fetchWithAuth<CurrencyPairAnalyticsApiResponse["data"]>(
        "/api/admin/analytics/currency-pairs",
        accessToken,
      ),
      fetchWithAuth<WalletAnalyticsApiResponse["data"]>("/api/admin/analytics/wallets", accessToken),
      fetchWithAuth<CustomerAnalyticsApiResponse["data"]>("/api/admin/analytics/customers", accessToken),
      // Using corridors API for country data
      fetchWithAuth<CountryAnalyticsApiResponse["data"]>("/api/admin/corridors/top-sending-countries", accessToken),
      fetchWithAuth<CountryAnalyticsApiResponse["data"]>("/api/admin/corridors/top-receiving-countries", accessToken),
      // New Analytics APIs
      fetchWithAuth<ProductAnalyticsResponse["data"]>("/api/admin/analytics/product/dau", accessToken),
      fetchWithAuth<ProductAnalyticsResponse["data"]>("/api/admin/analytics/product/wau", accessToken),
      fetchWithAuth<ProductAnalyticsResponse["data"]>("/api/admin/analytics/product/mau", accessToken),
      fetchWithAuth<TransactionAnalyticsResponse["data"]>("/api/admin/analytics/transaction/frequency", accessToken),
      fetchWithAuth<RevenueAnalyticsResponse["data"]>("/api/admin/analytics/revenue/gtv", accessToken),
    ]);

    // Collect errors for documentation and detailed logging
    const apiErrors: Array<{ endpoint: string; error: string }> = [];

    // Log start of data fetch for debugging
    console.log("[General Metrics] Starting analytics data fetch...");

    if (!profitResult.success && profitResult.error) {
      apiErrors.push({ endpoint: profitResult.endpoint, error: profitResult.error });
      console.warn("[General Metrics] Profit Analytics - No data:", {
        endpoint: profitResult.endpoint,
        error: profitResult.error,
      });
    }
    if (!currencyPairResult.success && currencyPairResult.error) {
      apiErrors.push({ endpoint: currencyPairResult.endpoint, error: currencyPairResult.error });
      console.warn("[General Metrics] Currency Pair Analytics - No data:", {
        endpoint: currencyPairResult.endpoint,
        error: currencyPairResult.error,
      });
    }
    if (!walletResult.success && walletResult.error) {
      apiErrors.push({ endpoint: walletResult.endpoint, error: walletResult.error });
      console.warn("[General Metrics] Wallet Analytics - No data:", {
        endpoint: walletResult.endpoint,
        error: walletResult.error,
      });
    }
    if (!customerResult.success && customerResult.error) {
      apiErrors.push({ endpoint: customerResult.endpoint, error: customerResult.error });
      console.warn("[General Metrics] Customer Analytics - No data:", {
        endpoint: customerResult.endpoint,
        error: customerResult.error,
      });
    }
    if (!topSendingCountriesResult.success && topSendingCountriesResult.error) {
      apiErrors.push({ endpoint: topSendingCountriesResult.endpoint, error: topSendingCountriesResult.error });
      console.warn("[General Metrics] Top Sending Countries - No data:", {
        endpoint: topSendingCountriesResult.endpoint,
        error: topSendingCountriesResult.error,
      });
    }
    if (!topReceivingCountriesResult.success && topReceivingCountriesResult.error) {
      apiErrors.push({ endpoint: topReceivingCountriesResult.endpoint, error: topReceivingCountriesResult.error });
      console.warn("[General Metrics] Top Receiving Countries - No data:", {
        endpoint: topReceivingCountriesResult.endpoint,
        error: topReceivingCountriesResult.error,
      });
    }
    // Note: We don't strictly fail on the new analytics metrics if they error, we just show 0/N/A

    // Summary log for debugging
    if (apiErrors.length > 0) {
      console.warn(`[General Metrics] ${apiErrors.length} API endpoint(s) failed:`, apiErrors.map(e => e.endpoint));
    } else {
      console.log("[General Metrics] All API endpoints succeeded");
    }

    // Transform data to cards (with fallback to dummy data)
    const profitCards = transformProfitAnalyticsToCards(
      profitResult.success ? (profitResult.data ?? null) : null,
      profitResult.error,
    );
    const currencyPairCards = transformCurrencyPairAnalyticsToCards(
      currencyPairResult.success ? (currencyPairResult.data ?? null) : null,
      currencyPairResult.error,
    );
    const walletCards = transformWalletAnalyticsToCards(
      walletResult.success ? (walletResult.data ?? null) : null,
      walletResult.error,
    );
    const customerCards = transformCustomerAnalyticsToCards(
      customerResult.success ? (customerResult.data ?? null) : null,
      customerResult.error,
    );
    const countryCards = transformCountryAnalyticsToCards(
      topSendingCountriesResult.success ? (topSendingCountriesResult.data ?? null) : null,
      topSendingCountriesResult.error,
    );

    // ========================================================================
    // Process New Analytics Data
    // ========================================================================

    // Extract Product Metrics
    const dau = dauResult.success && dauResult.data?.dau && dauResult.data.dau.length > 0
      ? dauResult.data.dau[dauResult.data.dau.length - 1].count
      : 0;

    const wau = wauResult.success && wauResult.data?.wau && wauResult.data.wau.length > 0
      ? wauResult.data.wau[wauResult.data.wau.length - 1].count
      : 0;

    const mau = mauResult.success && mauResult.data?.mau && mauResult.data.mau.length > 0
      ? mauResult.data.mau[mauResult.data.mau.length - 1].count
      : 0;

    // Extract Revenue/Transaction Metrics
    const gtv = gtvResult.success && typeof gtvResult.data?.gtv === 'number' ? gtvResult.data.gtv : 0;

    // Transaction Frequency returns array of { date, count }. Sum them or take latest?
    // Usually "frequency" implies over time. We want "Total Transactions".
    // If it returns a list, we might need to sum it for the period.
    // Assuming it returns daily counts.
    let totalTransactions = 0;
    if (transactionFreqResult.success && transactionFreqResult.data?.frequency) {
      totalTransactions = transactionFreqResult.data.frequency.reduce((sum, item) => sum + (item.count || 0), 0);
    }

    // Derived Metrics
    const avgTransactionValue = totalTransactions > 0 ? gtv / totalTransactions : 0;

    const totalCustomers = customerResult.success && customerResult.data?.lifetimeValue?.totalCustomers
      ? customerResult.data.lifetimeValue.totalCustomers
      : 0;

    const avgTransactionsPerCustomer = totalCustomers > 0 ? totalTransactions / totalCustomers : 0;

    const newMetricCards: MetricCardData[] = [
      {
        id: "active-users-daily",
        title: "Daily Active Users",
        value: formatNumber(dau),
        change: "+0%",
        trend: "neutral",
        subtitle: "Unique users today",
        isDemoData: false, // 0 is real data
        currency: "all"
      },
      {
        id: "active-users-weekly",
        title: "Weekly Active Users",
        value: formatNumber(wau),
        change: "+0%",
        trend: "neutral",
        subtitle: "Unique users last 7 days",
        isDemoData: false,
        currency: "all"
      },
      {
        id: "active-users-monthly",
        title: "Monthly Active Users",
        value: formatNumber(mau),
        change: "+0%",
        trend: "neutral",
        subtitle: "Unique users last 30 days",
        isDemoData: false,
        currency: "all"
      },
      {
        id: "total-volume-gtv",
        title: "Total Transaction Volume (GTV)",
        value: formatCurrency(gtv, "USD"),
        change: "+0%",
        trend: "neutral",
        subtitle: "Gross transaction volume",
        isDemoData: false,
        currency: "all"
      },
      {
        id: "total-transaction-count-real",
        title: "Total Transactions",
        value: formatNumber(totalTransactions),
        change: "+0%",
        trend: "neutral",
        subtitle: "Successful transactions",
        isDemoData: false,
        currency: "all"
      },
      {
        id: "avg-transaction-value",
        title: "Average Transaction Value",
        value: formatCurrency(avgTransactionValue, "USD"),
        change: "+0%",
        trend: "neutral",
        subtitle: "GTV / Total Transactions",
        isDemoData: false,
        currency: "all"
      },
      {
        id: "avg-transactions-per-customer",
        title: "Avg Transactions / Customer",
        value: avgTransactionsPerCustomer.toFixed(1),
        change: "+0%",
        trend: "neutral",
        subtitle: "Transactions / Total Customers",
        isDemoData: false,
        currency: "all"
      }
    ];

    // Combine all metric cards
    const metricCards: MetricCardData[] = [
      ...profitCards,
      ...customerCards,
      ...countryCards,
      ...newMetricCards, // Add the new analytics cards
      ...currencyPairCards,
      ...walletCards,
    ];

    // ========================================================================
    // FILTER: Only show general metrics on main metrics page
    // User-specific metrics are filtered out here
    // ========================================================================

    /**
     * Helper function to extract the base metric ID without currency suffix.
     * Examples:
     *   - "gross-revenue-all" → "gross-revenue"
     *   - "gross-revenue-ngn" → "gross-revenue"
     *   - "total-wallets" → "total-wallets"
     */
    const getBaseMetricId = (cardId: string): string => {
      // Remove currency suffixes: -all, -ngn, -kes, -ghs, -zar
      return cardId.replace(/-all$|-ngn$|-kes$|-ghs$|-zar$/i, "");
    };

    /**
     * Filter metric cards to only include those in the GENERAL_METRIC_IDS whitelist.
     * Also hide demo data cards to make it clear what's working.
     */
    const filteredMetricCards = metricCards.filter((card) => {
      const baseId = getBaseMetricId(card.id);
      const isGeneralMetric = GENERAL_METRIC_IDS.includes(baseId);

      // Hide demo data cards for now
      // We rely on isDemoData flag which should be accurate now.
      const isRealData = !card.isDemoData;

      // Log filtered out cards for debugging (only in development)
      if (!isGeneralMetric && process.env.NODE_ENV === "development") {
        console.log(`[Metrics Filter] Excluding non-general metric: ${card.id} (${card.title})`);
      }
      if (card.isDemoData && process.env.NODE_ENV === "development") {
        console.log(`[Metrics Filter] Hiding demo data card: ${card.id} (${card.title})`);
      }

      // Allow 0 values as long as they are NOT marked as demo/placeholder
      return isGeneralMetric && isRealData;
    });

    // Transform to charts - includes snapshot charts
    const snapshotCharts = transformToCharts(
      profitResult.success ? (profitResult.data ?? null) : null,
      currencyPairResult.success ? (currencyPairResult.data ?? null) : null,
      walletResult.success ? (walletResult.data ?? null) : null,
      {
        profit: profitResult.error,
        currencyPair: currencyPairResult.error,
        wallet: walletResult.error,
      },
    );

    // Monthly charts removed - no backend endpoint exists yet
    const monthlyCharts: ChartData[] = [];

    // Add country analytics charts (using corridors data)
    const countryCharts = transformCountryAnalyticsToCharts(
      topSendingCountriesResult.success ? (topSendingCountriesResult.data ?? null) : null,
      topSendingCountriesResult.error,
    );

    // Filter out old historical placeholder charts and combine with real data
    const filteredSnapshotCharts = snapshotCharts.filter(
      (chart) => !chart.id.endsWith("-historical") || chart.isDemoData === false,
    );

    const allCharts = [...filteredSnapshotCharts, ...monthlyCharts, ...countryCharts];

    const getBaseChartId = (chartId: string): string => {
      return chartId.replace(/-all$|-ngn$|-kes$|-ghs$|-zar$/i, "");
    };

    const filteredCharts = allCharts.filter((chart) => {
      const baseId = getBaseChartId(chart.id);
      const isGeneralChart = GENERAL_CHART_IDS.includes(baseId);

      // Hide demo data charts for now (user requested)
      const isRealData = !chart.isDemoData;

      // Log filtered out charts for debugging (only in development)
      if (!isGeneralChart && process.env.NODE_ENV === "development") {
        console.log(`[Charts Filter] Excluding non-general chart: ${chart.id} (${chart.title})`);
      }
      if (chart.isDemoData && process.env.NODE_ENV === "development") {
        console.log(`[Charts Filter] Hiding demo data chart: ${chart.id} (${chart.title})`);
      }

      return isGeneralChart && isRealData;
    });

    return {
      status: true,
      message:
        apiErrors.length > 0
          ? `Analytics data fetched with ${apiErrors.length} endpoint error(s)`
          : "Analytics data fetched successfully",
      data: {
        metricCards: filteredMetricCards, // ← Using filtered cards
        charts: filteredCharts, // ← Using filtered charts
      },
      apiErrors: apiErrors.length > 0 ? apiErrors : undefined,
    };
  } catch (error) {
    console.error("Error fetching analytics data:", error);

    // Return full dummy data on complete failure
    return {
      status: true,
      message: "Using demo data due to connection error",
      data: {
        metricCards: (dummyMetricCardsData as MetricCardData[]).map((card) => ({
          ...card,
          isDemoData: true,
          demoDataReason: "error" as DemoDataReason,
          demoDataMessage: error instanceof Error ? error.message : "Connection error",
        })),
        charts: (dummyChartsData as ChartData[]).map((chart) => ({
          ...chart,
          isDemoData: true,
          demoDataReason: "error" as DemoDataReason,
          demoDataMessage: error instanceof Error ? error.message : "Connection error",
        })),
      },
      apiErrors: [{ endpoint: "all", error: error instanceof Error ? error.message : "Unknown error" }],
    };
  }
}

export async function fetchAnalyticsDataByTimeRange(
  _timeRange: "weekly" | "monthly" | "quarterly" | "yearly",
): Promise<AnalyticsResponse | ApiError> {
  // TODO: Add date range parameters to API calls
  return fetchAnalyticsData();
}

export async function fetchCurrencyPairAnalytics(
  _sourceCurrency?: string,
  _targetCurrency?: string,
): Promise<AnalyticsResponse | ApiError> {
  // For now, just call the main function
  // TODO: Add currency pair filtering to API calls
  return fetchAnalyticsData();
}
